[versions]
# https://github.com/mikepenz/AboutLibraries/releases
aboutLibraries = "12.1.2"
# https://developer.android.com/build/releases/gradle-plugin
agp = "8.10.0"

# https://developer.android.com/tools/releases/platforms
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

# https://developer.android.com/jetpack/androidx/releases/activity
androidx-activityCompose = "1.10.1"
# https://developer.android.com/jetpack/androidx/releases/datastore
androidx-data-store = "1.1.7"
# https://developer.android.com/jetpack/androidx/releases/test
androidx-espresso-core = "3.6.1"
# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidx-lifecycle = "2.9.0"
# https://developer.android.com/jetpack/androidx/releases/navigation
# Controlled by compose multiplatform
androidx-navigationCompose = "2.9.0-beta02" # based on 2.9.0
# https://developer.android.com/jetpack/androidx/releases/test
androidx-test-junit = "1.2.1"
# https://developer.android.com/jetpack/androidx/releases/work
androidx-work = "2.10.1"
# https://github.com/coil-kt/coil/releases
coil = "3.2.0"
# https://github.com/JetBrains/compose-hot-reload/releases
compose-hotReload = "1.0.0-alpha10"
# https://github.com/JetBrains/compose-multiplatform/releases
compose-multiplatform = "1.8.1"
# https://github.com/Kotlin/dokka/releases
dokka = "2.0.0"
# https://developer.android.com/jetpack/androidx/releases/glance
glance = "1.1.1"
# https://github.com/touchlab/Kermit/releases
kermit = "2.0.5"
# https://github.com/InsertKoinIO/koin/releases
koin = "4.0.4"
# https://github.com/kotest/kotest/releases
kotest = "6.0.0.M4"
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.1.21"
# https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-coroutines = "1.10.2"
# https://github.com/Kotlin/kotlinx-datetime/releases
kotlinx-datetime = "0.6.2"
# https://github.com/goncalossilva/kotlinx-resources/releases
kotlinx-resource = "0.10.0"
# https://github.com/Kotlin/kotlinx.serialization/releases
kotlinx-serialization-json = "1.8.1"
# https://github.com/Kotlin/kotlinx-kover/releases
kover = "0.9.1"
# https://github.com/google/ksp/releases
ksp = "2.1.21-2.0.1"
# https://github.com/ktorio/ktor/releases
ktor = "3.1.2" # Depends on ktorfit
# https://github.com/Foso/Ktorfit/releases
ktorfit = "2.5.2"
# https://github.com/pinterest/ktlint/releases
ktlint-pinterest = "1.6.0"
# https://github.com/jlleitschuh/ktlint-gradle/releases
ktlint-plugin = "12.3.0"
# https://github.com/mrmans0n/compose-rules/releases
ktlint-compose = "0.4.22"
# https://github.com/JetBrains/skiko/releases
skiko = "0.9.4.2"
# https://square.github.io/okio/changelog/
okio = "3.11.0"
# https://github.com/kdroidFilter/Platform-Tools/releases
platformtools = "0.2.9"

[libraries]
# Kotlin - Kotlinx essentials
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-reflection = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
# Resources multiplatform
kotlinx-resources = { module = "com.goncalossilva:resources", version.ref = "kotlinx-resource" }
# Ktor
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-engine-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-client-resource = { group = "io.ktor", name = "ktor-client-resources", version.ref = "ktor" }
ktor-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
# Ktorfit
ktorfit-flow = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-converters-flow", version.ref = "ktorfit" }
ktorfit-light = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-lib-light", version.ref = "ktorfit" }
# Logger
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
kermit-koin = { module = "co.touchlab:kermit-koin", version.ref = "kermit" }
# Kotest
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
# Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-data-store-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-data-store" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigationCompose" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-work-kt = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
# Glance
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }

coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
# Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }

ktlint-compose = { module = "io.nlopez.compose.rules:ktlint", version.ref = "ktlint-compose" }

aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }

platformtools-darkmode = { module = "io.github.kdroidfilter:platformtools.darkmodedetector", version.ref = "platformtools" }
platformtools-permission = { module = "io.github.kdroidfilter:platformtools.permissionhandler", version.ref = "platformtools" }

# Okio
okio-core = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fake = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }

# Libraries can be bundled together for easier import
[bundles]
androidx-compose = [
#    "androidx-test-junit",
#    "androidx-espresso-core",
#    "androidx-constraintlayout",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-lifecycle-runtime-compose",
    "androidx-navigation-compose",
    "androidx-data-store-preferences"
]
koin = ["koin-compose", "koin-viewmodel-navigation"]
kotlinx-ecosystem = ["kotlinx-datetime", "kotlinx-serialization", "kotlinx-coroutines", "kotlin-reflection"]
ktorfit = [
    "ktorfit-light",
    "ktorfit-flow",
    "ktor-client-content-negotiation",
    "ktor-json",
    "ktor-client-resource",
    "ktor-client-logging"
]
testing = [
    "kotlin-test",
    "ktor-client-mock",
    "kotlinx-coroutines-test",
    "kotlinx-resources",
    "kotest-assertions-core",
    "kotest-assertions-json"
]

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinxResources = { id = "com.goncalossilva.resources", version.ref = "kotlinx-resource" }
kotlinxKover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
# Compose
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
# Compose desktop Hot reload
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hotReload" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
