[versions]
# https://github.com/mikepenz/AboutLibraries/releases
# aboutLibraries = "12.2.3"
# https://developer.android.com/build/releases/gradle-plugin
agp = "8.13.0"

# https://developer.android.com/tools/releases/platforms
android-compileSdk = "36"
android-minSdk = "30"
android-targetSdk = "36"

# https://developer.android.com/jetpack/androidx/releases/activity
androidx-activityCompose = "1.11.0"
# https://developer.android.com/jetpack/androidx/releases/datastore
androidx-data-store = "1.1.7"
# https://developer.android.com/jetpack/androidx/releases/test
# androidx-espresso-core = "3.6.1"
# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidx-lifecycle = "2.9.3"
# https://developer.android.com/jetpack/androidx/releases/navigation
# androidx-navigation-compose = "2.9.2"
# https://developer.android.com/jetpack/androidx/releases/test
androidx-test-core = "1.7.0"
androidx-test-junit = "1.3.0"
androidx-test-runner = "1.7.0"
androidx-test-rules = "1.7.0"
# https://developer.android.com/jetpack/androidx/releases/work
# androidx-work = "2.10.2"
# https://github.com/ajalt/clikt/releases
clikt = "5.0.3"
# https://github.com/coil-kt/coil/releases
coil = "3.3.0"
# https://github.com/JetBrains/compose-hot-reload/releases
# compose-hotReload = "1.0.0-alpha11"
# https://github.com/JetBrains/compose-multiplatform/releases
compose-multiplatform = "1.8.2"
# https://developer.android.com/develop/ui/compose/bom/bom-mapping
compose-bom = "2025.09.00"
# https://github.com/kingg22/deezer-client-kt/releases
deezer-client-kt = "2.1.0"
# https://developer.android.com/jetpack/androidx/releases/glance
# glance = "1.1.1"
# https://github.com/touchlab/Kermit/releases
kermit = "2.0.8"
# https://github.com/InsertKoinIO/koin/releases
koin = "4.1.1"
# https://github.com/LemonAppDev/konsist/releases
konsist = "0.17.3"
# https://github.com/kotest/kotest/releases
kotest = "6.0.3"
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.2.20"
# https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-coroutines = "1.10.2"
# https://github.com/goncalossilva/kotlinx-resources/releases
kotlinx-resource = "0.10.1"
# https://github.com/Kotlin/kotlinx-kover/releases
kover = "0.9.1"
# https://github.com/google/ksp/releases
ksp = "2.2.20-2.0.3"
# https://github.com/ktorio/ktor/releases
ktor = "3.3.0"
# https://github.com/kingg22/ktorgen/releases
ktorgen = "0.4.0"
# https://github.com/pinterest/ktlint/releases
ktlint-pinterest = "1.7.1"
# https://github.com/jlleitschuh/ktlint-gradle/releases
ktlint-plugin = "13.0.0"
# https://github.com/mrmans0n/compose-rules/releases
ktlint-compose = "0.4.27"
# https://github.com/JetBrains/skiko/releases
#skiko = "0.9.23"
# https://square.github.io/okio/changelog/
okio = "3.16.0"
# https://developer.android.com/jetpack/androidx/releases/navigation3
navigation3 = "1.0.0-alpha09"
# https://github.com/mockk/mockk/releases
mockk = "1.14.5"
# https://github.com/drewhamilton/Poko/releases
poko = "0.20.0"
# https://github.com/kingg22/vibrion-id3/releases
vibrion-id3 = "0.6.0"

[libraries]
# Kotlin - Kotlinx essentials
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
# kotlin-reflection = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
#kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
# kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
#kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
#kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# Resources multiplatform
kotlinx-resources = { group = "com.goncalossilva", name = "resources", version.ref = "kotlinx-resource" }

# Ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
#ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
# ktor-client-engine-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-engine-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
#ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
#ktor-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# ktorgen
ktorgen-annotations = { group = "io.github.kingg22", name = "ktorgen-annotations", version.ref = "ktorgen" }
ktorgen-compiler = { group = "io.github.kingg22", name = "ktorgen-compiler", version.ref = "ktorgen" }

# Logger
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
kermit-koin = { group = "co.touchlab", name = "kermit-koin", version.ref = "kermit" }

# Kotest
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { group = "io.kotest", name = "kotest-assertions-json", version.ref = "kotest" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activityCompose" }
androidx-data-store-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-data-store" }
# androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
# androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "androidx-lifecycle" }
# From compose multiplatform
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test = { module = "androidx.compose.ui:ui-test" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

compose-animation = { module = "androidx.compose.animation:animation" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }

compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable" }

compose-foundation = { module = "androidx.compose.foundation:foundation" }

compose-material = { module = "androidx.compose.material:material" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite" }

# Glance
#androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
#androidx-glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }

coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
# coil-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

# Koin
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
# koin-test = { group = "io.insert-koin", name = "koin-test" }
# koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-androidx-startup = { group = "io.insert-koin", name = "koin-androidx-startup" }
koin-compose = { group = "io.insert-koin", name = "koin-compose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }

# Konsist
konsist = { group = "com.lemonappdev", name = "konsist", version.ref = "konsist" }

ktlint-compose = { group = "io.nlopez.compose.rules", name = "ktlint", version.ref = "ktlint-compose" }

# aboutlibraries-compose-m3 = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutLibraries" }

# Okio
okio-core = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
# okio-fake = { group = "com.squareup.okio", name = "okio-fakefilesystem", version.ref = "okio" }

# Clikt
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }

# nav3
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }

# mockk
# mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }

# id3
vibrion-id3 = { group = "io.github.kingg22", name = "vibrion-id3", version.ref = "vibrion-id3" }

# deezer api client
deezer-client-kt = { group = "io.github.kingg22", name = "deezer-client-kt", version.ref = "deezer-client-kt" }

# Libraries can be bundled together for easier import
[bundles]
testing = [
    "kotlin-test",
    "kotlinx-coroutines-test",
    "kotest-assertions-core",
]
testing-ktor = ["ktor-client-mock", "kotlinx-resources", "kotest-assertions-json"]

[plugins]
# aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
# androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# Compose
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
# Compose desktop Hot reload
# composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hotReload" }
# dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinxKover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlinxResources = { id = "com.goncalossilva.resources", version.ref = "kotlinx-resource" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }
