[versions]
# https://github.com/mikepenz/AboutLibraries/releases
about-libraries = "13.2.1"

# https://developer.android.com/build/releases/gradle-plugin
agp = "9.0.0"

# https://developer.android.com/tools/releases/platforms
android-compileSdk = "36"
android-minSdk = "30"

# https://developer.android.com/jetpack/androidx/releases/activity
androidx-activity-compose = "1.12.2"

# https://developer.android.com/jetpack/androidx/releases/datastore
androidx-data-store = "1.2.0"

# See CMP https://github.com/JetBrains/compose-multiplatform/releases based on
# https://developer.android.com/jetpack/androidx/releases/lifecycle
jetbrains-lifecycle = "2.10.0-alpha06"
androidx-lifecycle = "2.10.0"

# https://developer.android.com/jetpack/androidx/releases/paging
androidx-paging = "3.4.0-rc01"

# https://github.com/coil-kt/coil/releases
coil = "3.3.0"

# Based on the version provided by compose-multiplatform
# https://github.com/JetBrains/compose-hot-reload/releases
compose-hot-reload = "1.0.0"

# https://github.com/JetBrains/compose-multiplatform/releases Material dependencies are separeted
compose-material3 = "1.10.0-alpha05"

# https://github.com/JetBrains/compose-multiplatform/releases
compose-multiplatform = "1.10.0"

# https://developer.android.com/develop/ui/compose/bom/bom-mapping
compose-bom = "2026.01.00"

# https://github.com/kingg22/deezer-client-kt/releases
deezer-client-kt = "3.1.0"

# https://developer.android.com/jetpack/androidx/releases/glance
glance = "1.1.1"

# https://github.com/touchlab/Kermit/releases
kermit = "2.0.8"

# https://github.com/InsertKoinIO/koin/releases
koin = "4.1.1"

# https://github.com/JetBrains/kotlin/releases
kotlin = "2.3.10"

# https://github.com/ktorio/ktor/releases
ktor = "3.4.0"

# https://github.com/pinterest/ktlint/releases
ktlint-pinterest = "1.8.0"

# https://github.com/jlleitschuh/ktlint-gradle/releases
ktlint-plugin = "14.0.1"

# https://github.com/mrmans0n/compose-rules/releases
ktlint-compose = "0.5.5"

# https://developer.android.com/jetpack/androidx/releases/media3?hl=es-419
media3 = "1.9.0"

# https://developer.android.com/jetpack/androidx/releases/navigation3
navigation3 = "1.0.0"

# https://github.com/JetBrains/compose-multiplatform/releases
# https://mvnrepository.com/artifact/org.jetbrains.androidx.navigation3/navigation3-ui
jetbrains-nav3 = "1.0.0-alpha06"

# https://github.com/getsentry/sentry-java/releases
sentry-bom = "8.31.0"

# https://github.com/getsentry/sentry-android-gradle-plugin/releases
sentry-plugin = "6.0.0-rc.1"

# https://github.com/getsentry/sentry-kotlin-multiplatform/releases
sentry-kotlin-multiplatform = "0.23.0"

# https://mvnrepository.com/artifact/org.slf4j/slf4j-android
slf4jAndroid = "1.7.36"

# https://github.com/ComposeGears/Valkyrie/releases
valkyrie-gradle = "0.3.0"

[libraries]
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing" }

# Ktor
ktor-client-engine-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }

# Logger
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-data-store-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "androidx-data-store" }
androidx-data-store-preferences-android = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-data-store" }

# use jetbrains fork when use CMP or KMP
jetbrains-multiplatform-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose-multiplatform" }
compose-hot-reload-annotations = { module = "org.jetbrains.compose.hot-reload:hot-reload-annotations", version.ref = "compose-hot-reload" }

# ------------------------------------------------------------------------------
# Androidx Lifecycle
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-nav3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }

jetbrains-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "jetbrains-lifecycle" }
jetbrains-lifecycle-viewmodel-nav3 = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "jetbrains-lifecycle" }

# ------------------------------------------------------------------------------
# AndroidX Compose BOM (Android only) Track https://youtrack.jetbrains.com/issue/CMP-2502
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
# using compose-multiplatform version because CMP currently don't provide a BOM https://youtrack.jetbrains.com/issue/CMP-6654

# ------------------------------------------------------------------------------
# Compose UI (Core)
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }

jetbrains-compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose-multiplatform" }

androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
jetbrains-compose-ui-util = { group = "org.jetbrains.compose.ui", name = "ui-util", version.ref = "compose-multiplatform" }

# ------------------------------------------------------------------------------
# Compose UI – Tooling & Preview
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

jetbrains-compose-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose-multiplatform" }
jetbrains-compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-multiplatform" }

# ------------------------------------------------------------------------------
# Compose UI – Testing
# ------------------------------------------------------------------------------
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

jetbrains-compose-ui-test = { group = "org.jetbrains.compose.ui", name = "ui-test", version.ref = "compose-multiplatform" }
jetbrains-compose-ui-test-junit4 = { group = "org.jetbrains.compose.ui", name = "ui-test-junit4", version.ref = "compose-multiplatform" }

# Compose Animation
# ------------------------------------------------------------------------------
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }

jetbrains-compose-animation = { group = "org.jetbrains.compose.animation", name = "animation", version.ref = "compose-multiplatform" }
jetbrains-compose-animation-graphics = { group = "org.jetbrains.compose.animation", name = "animation-graphics", version.ref = "compose-multiplatform" }

# Compose Runtime
# ------------------------------------------------------------------------------
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-saveable = { group = "androidx.compose.runtime", name = "runtime-saveable" }

jetbrains-compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-multiplatform" }
jetbrains-compose-runtime-saveable = { group = "org.jetbrains.compose.runtime", name = "runtime-saveable", version.ref = "compose-multiplatform" }

# Compose Foundation
# ------------------------------------------------------------------------------
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }

jetbrains-compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-multiplatform" }

# Compose Material Icons (deprecated**)
# ------------------------------------------------------------------------------
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

jetbrains-compose-material-icons = { group = "org.jetbrains.compose.material", name = "material-icons-core", version = "1.7.3" }
jetbrains-compose-material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version = "1.7.3" }

# Compose Material 3 (JetBrains fork with separate version)
# ------------------------------------------------------------------------------
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }

jetbrains-compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-material3" }
jetbrains-compose-material3-navigation-suite = { group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "compose-material3" }

# Glance
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }
androidx-glance-appwidget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "glance" }
androidx-glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "glance" }

coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
coil-network-cache-control = { group = "io.coil-kt.coil3", name = "coil-network-cache-control", version.ref = "coil" }

# Koin
koin-androidx-startup = { group = "io.insert-koin", name = "koin-androidx-startup", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }

ktlint-compose = { group = "io.nlopez.compose.rules", name = "ktlint", version.ref = "ktlint-compose" }

aboutlibraries-compose-m3 = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "about-libraries" }

# nav3
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }

jetbrains-navigation3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "jetbrains-nav3" }

# paging3
androidx-paging3-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }

# id3
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4jAndroid" }

# deezer api client
deezer-client-kt = { group = "io.github.kingg22", name = "deezer-client-kt", version.ref = "deezer-client-kt" }

# exoplayer
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }

# sentry
sentry-bom = { group = "io.sentry", name = "sentry-bom", version.ref = "sentry-bom" }
sentry-kotlin-multiplatform = { module = "io.sentry:sentry-kotlin-multiplatform", version.ref = "sentry-kotlin-multiplatform" }
sentry-kt = { module = "io.sentry:sentry-kotlin-extensions" }
sentry-android = { module = "io.sentry:sentry-android-core" }
sentry-compose-android = { module = "io.sentry:sentry-compose-android" }
sentry-ktor-client = { module = "io.sentry:sentry-ktor-client" }

# Libraries can be bundled together for easier import
[bundles]

[plugins]
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about-libraries" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
sentry = { id = "io.sentry.android.gradle", version.ref = "sentry-plugin" }
sentry-compiler = { id = "io.sentry.kotlin.compiler.gradle", version.ref = "sentry-plugin" }
valkyrie = { id = "io.github.composegears.valkyrie", version.ref = "valkyrie-gradle" }
